// Mock data for the dashboard

// Batches data
export const batches = [
  {
    batchId: "B-2023-001",
    status: "Active",
    currentProcess: "Cutting",
    totalDiamonds: 120,
    totalCarats: 85.5,
    assignedTo: "John Smith",
    source: "Sierra Leone",
    createdDate: "2023-01-15",
    notes: "High quality rough diamonds, expected premium grade output.",
  },
  {
    batchId: "B-2023-002",
    status: "Active",
    currentProcess: "Polishing",
    totalDiamonds: 95,
    totalCarats: 62.3,
    assignedTo: "Maria Rodriguez",
    source: "Botswana",
    createdDate: "2023-02-03",
    notes: "Medium to high quality, some color variations.",
  },
  {
    batchId: "B-2023-003",
    status: "Completed",
    currentProcess: "Packaging",
    totalDiamonds: 150,
    totalCarats: 103.7,
    assignedTo: "David Chen",
    source: "Russia",
    createdDate: "2023-02-18",
    notes: "Completed ahead of schedule. Excellent clarity overall.",
  },
  {
    batchId: "B-2023-004",
    status: "Pending",
    currentProcess: "Sorting",
    totalDiamonds: 200,
    totalCarats: 145.2,
    assignedTo: "Unassigned",
    source: "Canada",
    createdDate: "2023-03-05",
    notes: "Awaiting initial quality assessment.",
  },
  {
    batchId: "B-2023-005",
    status: "Active",
    currentProcess: "Grading",
    totalDiamonds: 80,
    totalCarats: 56.8,
    assignedTo: "Sarah Johnson",
    source: "South Africa",
    createdDate: "2023-03-12",
    notes: "Premium quality batch, expected high market value.",
  },
  {
    batchId: "B-2023-006",
    status: "On Hold",
    currentProcess: "Cutting",
    totalDiamonds: 110,
    totalCarats: 78.4,
    assignedTo: "Michael Wong",
    source: "Angola",
    createdDate: "2023-03-20",
    notes: "On hold due to equipment maintenance.",
  },
  {
    batchId: "B-2023-007",
    status: "Active",
    currentProcess: "Sorting",
    totalDiamonds: 175,
    totalCarats: 124.6,
    assignedTo: "Emma Davis",
    source: "Namibia",
    createdDate: "2023-04-02",
    notes: "Initial assessment shows promising quality.",
  },
  {
    batchId: "B-2023-008",
    status: "Pending",
    currentProcess: "Sorting",
    totalDiamonds: 130,
    totalCarats: 92.5,
    assignedTo: "Unassigned",
    source: "Zimbabwe",
    createdDate: "2023-04-15",
    notes: "Awaiting specialized equipment for processing.",
  },
  {
    batchId: "B-2023-009",
    status: "Active",
    currentProcess: "Polishing",
    totalDiamonds: 90,
    totalCarats: 64.2,
    assignedTo: "Robert Kim",
    source: "Australia",
    createdDate: "2023-04-28",
    notes: "Good progress, expected completion in 2 weeks.",
  },
  {
    batchId: "B-2023-010",
    status: "Completed",
    currentProcess: "Certification",
    totalDiamonds: 105,
    totalCarats: 74.8,
    assignedTo: "Lisa Patel",
    source: "Tanzania",
    createdDate: "2023-05-10",
    notes: "All diamonds certified with GIA standards.",
  },
];

// Employees data
export const employees = [
  {
    id: "E001",
    name: "John Smith",
    email: "john.smith@diamond.com",
    position: "Senior Cutter",
    department: "Production",
    status: "Active",
    assignedTasks: 3,
    completedTasks: 28,
    performance: 92,
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "E002",
    name: "Maria Rodriguez",
    email: "maria.r@diamond.com",
    position: "Master Polisher",
    department: "Production",
    status: "Active",
    assignedTasks: 2,
    completedTasks: 31,
    performance: 95,
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "E003",
    name: "David Chen",
    email: "david.c@diamond.com",
    position: "Gemologist",
    department: "Quality Control",
    status: "Active",
    assignedTasks: 4,
    completedTasks: 25,
    performance: 88,
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "E004",
    name: "Sarah Johnson",
    email: "sarah.j@diamond.com",
    position: "Grading Specialist",
    department: "Quality Control",
    status: "Active",
    assignedTasks: 2,
    completedTasks: 22,
    performance: 90,
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "E005",
    name: "Michael Wong",
    email: "michael.w@diamond.com",
    position: "Cutter",
    department: "Production",
    status: "On Leave",
    assignedTasks: 0,
    completedTasks: 18,
    performance: 85,
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "E006",
    name: "Emma Davis",
    email: "emma.d@diamond.com",
    position: "Sorter",
    department: "Inventory",
    status: "Active",
    assignedTasks: 3,
    completedTasks: 20,
    performance: 87,
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "E007",
    name: "Robert Kim",
    email: "robert.k@diamond.com",
    position: "Polisher",
    department: "Production",
    status: "Active",
    assignedTasks: 2,
    completedTasks: 19,
    performance: 82,
    avatar: "/placeholder.svg?height=40&width=40",
  },
  {
    id: "E008",
    name: "Lisa Patel",
    email: "lisa.p@diamond.com",
    position: "Certification Specialist",
    department: "Quality Control",
    status: "Active",
    assignedTasks: 1,
    completedTasks: 24,
    performance: 91,
    avatar: "/placeholder.svg?height=40&width=40",
  },
];

// Tasks data
export const tasks = [
  {
    id: "T001",
    title: "Cut Batch B-2023-001",
    description: "Perform precision cutting on rough diamonds",
    assignedTo: "E001",
    batchId: "B-2023-001",
    status: "In Progress",
    priority: "High",
    dueDate: "2023-06-15",
  },
  {
    id: "T002",
    title: "Polish Batch B-2023-002",
    description: "Complete final polishing phase",
    assignedTo: "E002",
    batchId: "B-2023-002",
    status: "In Progress",
    priority: "Medium",
    dueDate: "2023-06-18",
  },
  {
    id: "T003",
    title: "Grade Batch B-2023-005",
    description: "Perform quality grading according to GIA standards",
    assignedTo: "E004",
    batchId: "B-2023-005",
    status: "Pending",
    priority: "High",
    dueDate: "2023-06-20",
  },
  {
    id: "T004",
    title: "Sort Batch B-2023-007",
    description: "Initial sorting and classification",
    assignedTo: "E006",
    batchId: "B-2023-007",
    status: "In Progress",
    priority: "Medium",
    dueDate: "2023-06-14",
  },
  {
    id: "T005",
    title: "Polish Batch B-2023-009",
    description: "Second phase polishing",
    assignedTo: "E007",
    batchId: "B-2023-009",
    status: "In Progress",
    priority: "Medium",
    dueDate: "2023-06-22",
  },
  {
    id: "T006",
    title: "Certify Batch B-2023-003",
    description: "Complete certification documentation",
    assignedTo: "E008",
    batchId: "B-2023-003",
    status: "Completed",
    priority: "High",
    dueDate: "2023-06-10",
  },
  {
    id: "T007",
    title: "Quality Check Batch B-2023-002",
    description: "Perform mid-process quality verification",
    assignedTo: "E003",
    batchId: "B-2023-002",
    status: "Completed",
    priority: "High",
    dueDate: "2023-06-08",
  },
  {
    id: "T008",
    title: "Cut Batch B-2023-006",
    description: "Resume cutting after maintenance",
    assignedTo: "E001",
    batchId: "B-2023-006",
    status: "Pending",
    priority: "Low",
    dueDate: "2023-06-25",
  },
  {
    id: "T009",
    title: "Inventory Audit",
    description: "Perform monthly inventory reconciliation",
    assignedTo: "E006",
    batchId: null,
    status: "Pending",
    priority: "Medium",
    dueDate: "2023-06-30",
  },
  {
    id: "T010",
    title: "Equipment Maintenance",
    description: "Scheduled maintenance for cutting machines",
    assignedTo: "E001",
    batchId: null,
    status: "Completed",
    priority: "Low",
    dueDate: "2023-06-05",
  },
];

// Notifications
export const notifications = [
  {
    id: "N001",
    title: "Batch B-2023-003 Completed",
    message: "The batch has been fully processed and is ready for shipping.",
    timestamp: "2023-06-10T14:30:00",
    read: false,
  },
  {
    id: "N002",
    title: "New Task Assigned",
    message: "You have been assigned to grade Batch B-2023-005.",
    timestamp: "2023-06-09T10:15:00",
    read: true,
  },
  {
    id: "N003",
    title: "Maintenance alert",
    message: "Scheduled maintenance for polishing equipment on June 15.",
    timestamp: "2023-06-08T16:45:00",
    read: false,
  },
];

// Revenue data for chart
export const revenueData = [
  { month: "Jan", revenue: 120000, profit: 42000 },
  { month: "Feb", revenue: 145000, profit: 50750 },
  { month: "Mar", revenue: 135000, profit: 47250 },
  { month: "Apr", revenue: 160000, profit: 56000 },
  { month: "May", revenue: 175000, profit: 61250 },
  { month: "Jun", revenue: 190000, profit: 66500 },
];
